apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: keycloak
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "4"
    homelab/values-path: platform/keycloak/values.yaml
spec:
  project: default
  sources:
    - repoURL: https://charts.bitnami.com/bitnami
      chart: keycloak
      targetRevision: 25.2.0
      helm:
        valueFiles:
          - $values/platform/keycloak/values.yaml
    - repoURL: https://github.com/rorobig/homelab-gitops.git
      targetRevision: main
      ref: values
  destination:
    server: https://kubernetes.default.svc
    namespace: keycloak
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
