apiVersion: argoproj.io/v1alpha1
kind: Application
metadata:
  name: shared-gateway
  namespace: argocd
  annotations:
    argocd.argoproj.io/sync-wave: "2"
spec:
  project: default
  source:
    repoURL: https://github.com/rorobig/homelab-gitops.git
    targetRevision: main
    path: platform/networking/shared-gateway
  destination:
    server: https://kubernetes.default.svc
    namespace: traefik
  syncPolicy:
    automated:
      prune: true
      selfHeal: true
    syncOptions:
      - CreateNamespace=true
