apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization
namespace: podinfo-dev
resources:
  - ../../base
images:
  - name: ghcr.io/stefanprodan/podinfo
    newTag: 6.14.0
patches:
  - target:
      kind: HTTPRoute
      name: podinfo
    patch: |-
      - op: replace
        path: /spec/hostnames/0
        value: podinfo-dev.home.arpa
